name: CI Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install dependencies
        run: C:\msys64\usr\bin\pacman --noconfirm -S mingw-w64-x86_64-gtk4 mingw-w64-x86_64-pkgconf mingw-w64-x86_64-gcc
      - name: Set PATH
        shell: bash
        run: |
          echo "C:\msys64\mingw64\include" >> $GITHUB_PATH
          echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
          echo "C:\msys64\mingw64\lib" >> $GITHUB_PATH

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable-x86_64-pc-windows-gnu

      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose -- --nocapture
        env:
          RUST_BACKTRACE: 1
