name: Release Linux

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libgtk-3-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-deb
          # use-tool-cache: true
      - name: Make deb
        id: make-deb
        run: |
          make deb
      - uses: softprops/action-gh-release@v1
        with:
          files: target/debian/password-storage*.deb
