name: Release Windows

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable-x86_64-pc-windows-gnu
      - name: Set PATH
        shell: bash
        run: |
          echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
          echo "C:\msys64\usr\bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: pacman --noconfirm -S mingw-w64-x86_64-gtk3 mingw-w64-x86_64-pkg-config
      - name: Set PKG_CONFIG_PATH
        shell: bash
        run: echo "PKG_CONFIG_PATH=/mingw64/lib/pkgconfig" >> $GITHUB_ENV
      - name: Set RUSTFLAGS
        shell: bash
        run: echo "RUSTFLAGS=-L C:\msys64\mingw64\lib" >> $GITHUB_ENV
      - name: Build
        run: cargo build --verbose --release

      - name: Package
        run: |
          mkdir win
          copy .\\target\\release\\password-storage.exe win
          "C:\\Program Files (x86)\\Inno Setup 6\\ISCC.exe" "/DVersion=${{ github.event.release.tag_name }}" ".\\windows\\setup.iss"
        shell: cmd

      - uses: softprops/action-gh-release@v1
        with:
          files: .\PasswordStorage-*.*
