name: Release Linux

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install flatpak
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends flatpak flatpak-builder
      - run: flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      - run: make flatpak
      - uses: softprops/action-gh-release@v1
        with:
          files: dev.andy128k.password-storage.flatpak
