name: Release macos

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install dependencies
        run: brew install pkg-config gtk4 librsvg
      - name: Make dmg
        id: make-dmg
        run: |
          VERSION=${{ github.event.release.tag_name }} make osx_app
      - uses: softprops/action-gh-release@v1
        with:
          files: target/dmg/PasswordStorage*.dmg
