name: Release macos

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions/setup-node@v1
      - name: Install dependencies
        run: brew install pkg-config gtk+3 librsvg
      - name: Make dmg
        id: make-dmg
        run: |
          VERSION=${{ github.event.release.tag_name }} make osx_app
      - uses: softprops/action-gh-release@v1
        with:
          files: target/dmg/PasswordStorage*.dmg
